### ISSUE TITLE
Support windows or mac wheel packages?

### ISSUE THREAD

**Issue by j55blanchet** [aldebaran/libqi-python#20]
I'm looking to be able to interface with the Nao6 robot from my lab computer (running windows), and my personal laptop (running macOS on apple silicoln). From [this thread](https://github.com/ros-naoqi/libqi-release/issues/4), I understand that using libqi directly is the recommended way to interact with Nao robots going forward. That's fine with me - I'm looking to get connected with the Nao using python3.

I can see that the latest release (3.1.4](https://github.com/aldebaran/libqi-python/releases/tag/qi-python-v3.1.4) now has prebuilt wheels for linux x64, supporting python versions 3.7-3.11. Yey! Are there plans to offer prebuilt wheels for windows or macOS in the future? (and preferably, uploaded on pypi for installation via pip?)

**Comment by nyibbang** [comment]
Hello @j55blanchet,

I will upload the Linux x86_64 wheels on PyPI as soon as possible. However, I am unable to build for Windows & MacOS at the moment because I don't have machines running on these OS, I only have a Linux machine to use as a build server. Crossbuilding for these platforms is pretty much out of the table, so the only solution I can think of would be to set up Github Actions and use Github hosted runners, which offer Windows & MacOS machines. I might do it some day but I can't make any promise.

In the mean time, I updated the README with a detailed description on how to build wheels using CMake + Conan. The procedure is as much as possible platform agnostic, so it should be possible to build wheels for Windows or MacOS (I've actually done it successfully not that long ago on a Apple M2 machine). If you have these tools and some time to allocate to this, I'd be glad if you would give it a try. And if you come across any problem during the procedure, I'd be happy to fix them.

**Comment by j55blanchet** [comment]
Thanks for uploading the wheels on PyPi and for updating the README!

I'll try to make time in the next week or two to build the wheels on windows & mac and let you know how that goes. 

Cheers!
